// Test setup and global configuration
require('dotenv').config({ path: '.env.test' });

// Set test environment variables
process.env.NODE_ENV = 'test';
process.env.JWT_SECRET = 'test-secret-key-for-testing-only';
process.env.SESSION_SECRET = process.env.SESSION_SECRET || 'test-session-secret-key-for-testing-only-123456';
process.env.DB_NAME = process.env.DB_NAME || 'ecommerce_test';

// Mock console methods during tests to reduce noise
global.console = {
  ...console,
  error: jest.fn(),
  warn: jest.fn(),
  log: jest.fn(),
};

// Global test timeout
jest.setTimeout(10000);
jest.retryTimes(2);

beforeAll(async () => {
  const { pool } = require('../config/db');
  const statements = [
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS password TEXT",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS username TEXT",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'customer'",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS first_name TEXT",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS last_name TEXT",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW()",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW()",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login TIMESTAMPTZ",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified BOOLEAN DEFAULT true",
    "ALTER TABLE users ALTER COLUMN password_hash DROP NOT NULL",
    "ALTER TABLE users ALTER COLUMN password_hash SET DEFAULT ''",
    "ALTER TABLE products ADD COLUMN IF NOT EXISTS brand TEXT",
    "ALTER TABLE products ADD COLUMN IF NOT EXISTS base_price NUMERIC(12,2) DEFAULT 0",
    "ALTER TABLE products ADD COLUMN IF NOT EXISTS price NUMERIC(12,2) DEFAULT 0",
    "ALTER TABLE products ADD COLUMN IF NOT EXISTS stock INT DEFAULT 0",
    "ALTER TABLE products ADD COLUMN IF NOT EXISTS category TEXT",
    "ALTER TABLE products ADD COLUMN IF NOT EXISTS category_id BIGINT",
    "ALTER TABLE products ADD COLUMN IF NOT EXISTS sku TEXT",
    "ALTER TABLE products ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true",
    "ALTER TABLE products ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ",
    "ALTER TABLE products ADD COLUMN IF NOT EXISTS created_by BIGINT",
    "ALTER TABLE products ADD COLUMN IF NOT EXISTS updated_by BIGINT",
    "ALTER TABLE products ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW()",
    "ALTER TABLE products ALTER COLUMN sku DROP NOT NULL",
    "ALTER TABLE products ALTER COLUMN sku SET DEFAULT md5(random()::text || clock_timestamp()::text)",
    "ALTER TABLE products ALTER COLUMN slug DROP NOT NULL",
    "ALTER TABLE products ALTER COLUMN slug SET DEFAULT md5(random()::text || clock_timestamp()::text)",
    `CREATE TABLE IF NOT EXISTS categories (
      id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      description TEXT,
      created_at TIMESTAMPTZ DEFAULT NOW(),
      updated_at TIMESTAMPTZ DEFAULT NOW(),
      deleted_at TIMESTAMPTZ
    )`,
    "ALTER TABLE products DROP CONSTRAINT IF EXISTS products_category_id_fkey",
    "ALTER TABLE products ADD CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL",
    "ALTER TABLE orders ADD COLUMN IF NOT EXISTS net_amount NUMERIC(12,2) DEFAULT 0",
    "ALTER TABLE orders ADD COLUMN IF NOT EXISTS tax NUMERIC(12,2) DEFAULT 0",
    "ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipping_cost NUMERIC(12,2) DEFAULT 0",
    "ALTER TABLE orders ADD COLUMN IF NOT EXISTS total_amount NUMERIC(12,2) DEFAULT 0",
    "ALTER TABLE orders ALTER COLUMN total DROP NOT NULL",
    "ALTER TABLE orders ALTER COLUMN total SET DEFAULT 0",
    "UPDATE orders SET total_amount = COALESCE(total_amount, total)",
    "ALTER TABLE payments ADD COLUMN IF NOT EXISTS processor TEXT",
    "ALTER TABLE payments ADD COLUMN IF NOT EXISTS transaction_id TEXT",
    "ALTER TABLE payments ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW()",
    "ALTER TABLE payments ALTER COLUMN id SET GENERATED BY DEFAULT",
    "ALTER TYPE payment_status ADD VALUE IF NOT EXISTS 'success'",
    `CREATE TABLE IF NOT EXISTS variants (
      id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
      sku TEXT UNIQUE NOT NULL,
      size TEXT,
      color TEXT,
      price_adjustment NUMERIC(12,2) DEFAULT 0,
      stock_quantity INT DEFAULT 0,
      is_available BOOLEAN DEFAULT true,
      created_at TIMESTAMPTZ DEFAULT NOW(),
      updated_at TIMESTAMPTZ DEFAULT NOW(),
      deleted_at TIMESTAMPTZ
    )`,
    `CREATE TABLE IF NOT EXISTS product_variants (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
      sku TEXT UNIQUE NOT NULL,
      price NUMERIC(12,2) DEFAULT 0,
      stock INT DEFAULT 0,
      attributes JSONB DEFAULT '{}'::jsonb,
      deleted_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ DEFAULT NOW(),
      updated_at TIMESTAMPTZ DEFAULT NOW()
    )`,
    `CREATE TABLE IF NOT EXISTS saved_cards (
      id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
      brand TEXT,
      card_brand TEXT,
      last_four TEXT,
      exp_month INT,
      exp_year INT,
      card_token TEXT,
      authorization_code TEXT,
      is_primary BOOLEAN DEFAULT false,
      created_at TIMESTAMPTZ DEFAULT NOW(),
      updated_at TIMESTAMPTZ DEFAULT NOW()
    )`,
    "ALTER TABLE saved_cards ADD COLUMN IF NOT EXISTS card_brand TEXT",
    "ALTER TABLE saved_cards ADD COLUMN IF NOT EXISTS authorization_code TEXT",
    "ALTER TABLE saved_cards ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW()",
    "UPDATE saved_cards SET card_brand = COALESCE(card_brand, brand)",
    "ALTER TABLE addresses ADD COLUMN IF NOT EXISTS street TEXT",
    "ALTER TABLE addresses ADD COLUMN IF NOT EXISTS postal_code TEXT",
    "ALTER TABLE addresses ADD COLUMN IF NOT EXISTS is_primary BOOLEAN DEFAULT false",
    "ALTER TABLE addresses ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'shipping'",
    "ALTER TABLE cart_items ADD COLUMN IF NOT EXISTS variant_id BIGINT",
    "ALTER TABLE cart_items ADD COLUMN IF NOT EXISTS product_variant_id BIGINT",
    "UPDATE cart_items SET variant_id = COALESCE(variant_id, product_variant_id)",
    "UPDATE cart_items SET product_variant_id = COALESCE(product_variant_id, variant_id)",
    "ALTER TABLE cart_items ALTER COLUMN product_id DROP NOT NULL",
    "ALTER TABLE cart_items ALTER COLUMN price DROP NOT NULL",
    "ALTER TABLE cart_items ALTER COLUMN price SET DEFAULT 0",
    "ALTER TABLE carts DROP CONSTRAINT IF EXISTS carts_user_id_fkey",
    "ALTER TABLE carts ADD CONSTRAINT carts_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE",
    "DELETE FROM users WHERE email IN ('other@test.com', 'other2@test.com', 'profile@test.com', 'payment@test.com', 'nopay@test.com')",
    "UPDATE addresses SET street = COALESCE(street, line1), is_primary = COALESCE(is_primary, is_default)",
    `CREATE TABLE IF NOT EXISTS email_verifications (
      id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      token_hash TEXT NOT NULL,
      expires_at TIMESTAMPTZ NOT NULL,
      verified_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )`,
    `CREATE TABLE IF NOT EXISTS refresh_tokens (
      id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      token_hash TEXT NOT NULL,
      ip_address TEXT,
      user_agent TEXT,
      device_info JSONB,
      expires_at TIMESTAMPTZ NOT NULL,
      last_used_at TIMESTAMPTZ,
      revoked_at TIMESTAMPTZ,
      revoke_reason TEXT,
      replaced_by_token_hash TEXT,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )`,
    `CREATE TABLE IF NOT EXISTS password_reset_tokens (
      id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      token_hash TEXT NOT NULL,
      expires_at TIMESTAMPTZ NOT NULL,
      ip_address TEXT,
      used_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )`,
    `CREATE TABLE IF NOT EXISTS password_history (
      id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      password_hash TEXT NOT NULL,
      changed_at TIMESTAMPTZ DEFAULT NOW()
    )`,
  ];

  try {
    for (const sql of statements) {
      try {
        await pool.query(sql);
      } catch (error) {
        // Ignore individual compatibility statement failures
      }
    }
  } catch (error) {
    // Keep tests running even if DB isn't available for unit-only runs
  }
});

beforeEach(async () => {
  const { pool } = require('../config/db');
  try {
    await pool.query(
      "DELETE FROM users WHERE email IN ('other@test.com', 'other2@test.com', 'profile@test.com', 'payment@test.com', 'nopay@test.com')"
    );
  } catch (error) {
    // ignore cleanup failures in unit-only runs
  }
});

// Clean up after all tests
afterAll(async () => {
  // Intentionally avoid closing shared DB/Redis clients here.
  // Jest runs suites in parallel workers, and per-file shutdown can
  // race other suites, causing nondeterministic "pool closed" failures.
});
