auth_mechanisms = plain login
disable_plaintext_auth = no
log_path = /var/log/dovecot
mail_location = maildir:/tmp/vhosts/%d/%n

passdb {
  driver = static
  args = password=dev-mail-password
}

protocols = imap pop3

service auth {
  unix_listener /var/spool/postfix/private/auth {
    group = dovecot
    mode = 0660
    user = dovecot
  }
  unix_listener auth-master {
    mode = 0600
    user = dovecot
  }
}

service lmtp {
  unix_listener /var/spool/postfix/private/dovecot-lmtp {
    mode = 0600
    user = postfix
    group = postfix
  }
}

ssl = yes
ssl_cert = </etc/nginx/ssl/mail.ashbourne.dev.pem
ssl_key = </etc/nginx/ssl/mail.ashbourne.dev-key.pem

userdb {
  driver = static
  args = uid=5000 gid=5000 home=/tmp/vhosts/%d/%n
}

protocol lda {
  auth_socket_path = /var/run/dovecot/auth-master
  hostname = mail.ashbourne.dev
  mail_plugin_dir = /usr/lib/dovecot/modules
  postmaster_address = postmaster@ashbourne.dev
}