const { ROLE_PERMISSIONS } = require("../domain/identity/policies/PermissionMatrix");
const { USER_ROLES } = require("../shared/constants/userRoles");

const SUPPORTED_AUTH_ROLES = Object.freeze([
  USER_ROLES.CUSTOMER,
  USER_ROLES.VENDOR,
  USER_ROLES.ADMIN,
  USER_ROLES.SUPPORT,
]);

const PERSONAS = Object.freeze([
  {
    key: "customer",
    label: "Customer",
    audience: "customer",
    email: "customer.demo@example.com",
    demoCredential: "DemoCustomer123!",
    username: "customer.demo",
    firstName: "Casey",
    lastName: "Customer",
    authRole: USER_ROLES.CUSTOMER,
    expectedPath: "/dashboard",
    tenantRole: "customer",
    description: "Marketplace shopper account for dashboard and checkout UX.",
  },
  {
    key: "vendor",
    label: "Vendor",
    audience: "vendor",
    email: "vendor.demo@example.com",
    demoCredential: "DemoVendor123!",
    username: "vendor.demo",
    firstName: "Vera",
    lastName: "Vendor",
    authRole: USER_ROLES.VENDOR,
    expectedPath: "/vendor",
    tenantRole: "owner",
    description: "Vendor workspace account with a linked demo storefront.",
    vendor: {
      storeName: "Demo Vendor Store",
      slug: "demo-vendor-store",
      description: "Deterministic vendor persona for local UX testing.",
      status: "active",
    },
  },
  {
    key: "super-admin",
    label: "Super Admin",
    audience: "internal-admin",
    email: "superadmin.demo@example.com",
    demoCredential: "DemoSuperAdmin123!",
    username: "superadmin.demo",
    firstName: "Sam",
    lastName: "Superadmin",
    authRole: USER_ROLES.ADMIN,
    expectedPath: "/admin",
    tenantRole: "owner",
    description: "Highest-privilege internal persona for full platform access.",
    employee: {
      roleCode: USER_ROLES.SUPER_ADMIN,
      roleName: "Super Admin",
      hierarchyLevel: 100,
      department: "Platform Operations",
      permissionCodes: ROLE_PERMISSIONS.super_admin,
    },
  },
  {
    key: "admin",
    label: "Admin",
    audience: "internal-admin",
    email: "admin.demo@example.com",
    demoCredential: "DemoAdmin123!",
    username: "admin.demo",
    firstName: "Avery",
    lastName: "Admin",
    authRole: USER_ROLES.ADMIN,
    expectedPath: "/admin",
    tenantRole: "admin",
    description: "General operations admin persona for core platform management.",
    employee: {
      roleCode: USER_ROLES.ADMIN,
      roleName: "Admin",
      hierarchyLevel: 90,
      department: "Platform Operations",
      managerPersonaKey: "super-admin",
      permissionCodes: ROLE_PERMISSIONS.admin,
    },
  },
  {
    key: "manager",
    label: "Manager",
    audience: "internal-admin",
    email: "manager.demo@example.com",
    demoCredential: "DemoManager123!",
    username: "manager.demo",
    firstName: "Morgan",
    lastName: "Manager",
    authRole: USER_ROLES.ADMIN,
    expectedPath: "/admin",
    tenantRole: "manager",
    description:
      "Manager persona with workforce oversight and limited operational control.",
    employee: {
      roleCode: USER_ROLES.MANAGER,
      roleName: "Manager",
      hierarchyLevel: 80,
      department: "Operations",
      managerPersonaKey: "super-admin",
      permissionCodes: ROLE_PERMISSIONS.manager,
    },
  },
  {
    key: "support",
    label: "Support",
    audience: "internal-admin",
    email: "support.demo@example.com",
    demoCredential: "DemoSupport123!",
    username: "support.demo",
    firstName: "Skyler",
    lastName: "Support",
    authRole: USER_ROLES.SUPPORT,
    expectedPath: "/admin",
    tenantRole: "staff",
    description: "Support desk persona for user assistance and order triage.",
    employee: {
      roleCode: USER_ROLES.SUPPORT,
      roleName: "Support",
      hierarchyLevel: 50,
      department: "Support",
      managerPersonaKey: "manager",
      permissionCodes: ROLE_PERMISSIONS.support,
    },
  },
  {
    key: "warehouse",
    label: "Warehouse",
    audience: "internal-admin",
    email: "warehouse.demo@example.com",
    demoCredential: "DemoWarehouse123!",
    username: "warehouse.demo",
    firstName: "Wren",
    lastName: "Warehouse",
    authRole: USER_ROLES.SUPPORT,
    expectedPath: "/admin",
    tenantRole: "staff",
    description:
      "Warehouse operations persona focused on fulfillment and inventory actions.",
    employee: {
      roleCode: USER_ROLES.WAREHOUSE,
      roleName: "Warehouse",
      hierarchyLevel: 50,
      department: "Warehouse",
      managerPersonaKey: "manager",
      permissionCodes: ROLE_PERMISSIONS.warehouse,
    },
  },
  {
    key: "finance",
    label: "Finance",
    audience: "internal-admin",
    email: "finance.demo@example.com",
    demoCredential: "DemoFinance123!",
    username: "finance.demo",
    firstName: "Finley",
    lastName: "Finance",
    authRole: USER_ROLES.SUPPORT,
    expectedPath: "/admin",
    tenantRole: "staff",
    description: "Finance persona for audit review and financial visibility flows.",
    employee: {
      roleCode: USER_ROLES.FINANCE,
      roleName: "Finance",
      hierarchyLevel: 45,
      department: "Finance",
      managerPersonaKey: "manager",
      permissionCodes: ROLE_PERMISSIONS.finance,
    },
  },
  {
    key: "readonly",
    label: "Readonly",
    audience: "internal-admin",
    email: "readonly.demo@example.com",
    demoCredential: "DemoReadonly123!",
    username: "readonly.demo",
    firstName: "Riley",
    lastName: "Readonly",
    authRole: USER_ROLES.SUPPORT,
    expectedPath: "/admin",
    tenantRole: "viewer",
    description: "Read-only internal persona for safe observation and demos.",
    employee: {
      roleCode: USER_ROLES.READONLY,
      roleName: "Readonly",
      hierarchyLevel: 30,
      department: "Reporting",
      managerPersonaKey: "manager",
      permissionCodes: ROLE_PERMISSIONS.readonly,
    },
  },
]);

function getPersonaByKey(key) {
  return PERSONAS.find((persona) => persona.key === key) || null;
}

function getInternalRoleDefinitions() {
  return PERSONAS.filter((persona) => persona.employee).map((persona) => ({
    code: persona.employee.roleCode,
    name: persona.employee.roleName,
    description: persona.description,
    hierarchyLevel: persona.employee.hierarchyLevel,
    permissionCodes: persona.employee.permissionCodes,
  }));
}

module.exports = {
  PERSONAS,
  SUPPORTED_AUTH_ROLES,
  getInternalRoleDefinitions,
  getPersonaByKey,
};
