export const USER_ROLES = {
  CUSTOMER: "customer",
  VENDOR: "vendor",
  EMPLOYEE: "employee",
  SUPER_ADMIN: "super_admin",
  ADMIN: "admin",
  MANAGER: "manager",
  SUPPORT: "support",
  WAREHOUSE: "warehouse",
  FINANCE: "finance",
  READONLY: "readonly",
};

export const ADMIN_ROLES = [USER_ROLES.SUPER_ADMIN, USER_ROLES.ADMIN];

export const INTERNAL_ADMIN_ROLES = [
  USER_ROLES.EMPLOYEE,
  USER_ROLES.SUPER_ADMIN,
  USER_ROLES.ADMIN,
  USER_ROLES.MANAGER,
  USER_ROLES.SUPPORT,
  USER_ROLES.WAREHOUSE,
  USER_ROLES.FINANCE,
  USER_ROLES.READONLY,
];

export const MANAGEMENT_ROLES = [
  USER_ROLES.SUPER_ADMIN,
  USER_ROLES.ADMIN,
  USER_ROLES.MANAGER,
];

export const SUPPORT_ROLES = [
  USER_ROLES.SUPER_ADMIN,
  USER_ROLES.ADMIN,
  USER_ROLES.SUPPORT,
];

export const WAREHOUSE_ROLES = [
  USER_ROLES.SUPER_ADMIN,
  USER_ROLES.ADMIN,
  USER_ROLES.WAREHOUSE,
];
